### ISSUE TITLE
Error in if (class(matCountData) == "SummarizedExperiment") { :    the condition has length > 1

### ISSUE THREAD

**Issue by rotemavr** [YosefLab/ImpulseDE2#31] opened 2022-06-13 08:48 UTC
hey 
My data set is a time series (10 time points) + M Vs F samples (batches) experiment.

i'm trying to run impulseDE2 case-control analysis and I get this error:
ImpulseDE2 for count data, v0.99.10
# Process input
Error in if (class(matCountData) == "SummarizedExperiment") { : 
  the condition has length > 1
Timing stopped at: 0 0 0
 

my df-annotation file matches my matobservedcounts 
my count table is scaled filtered and log2 transformed without any (0,NA, -inf) values
I'm not sure what is the "SummarizedExperiment" meaning and hoe to solve this. 
please help 
Rotem

**Comment by davidsebfischer** [comment] 2022-06-17 07:48
Hi Rotem, on first glance it looks as if the matCountData you supplied was a list? https://stackoverflow.com/questions/14170778/interpreting-condition-has-length-1-warning-from-if-function. Alternatively it might be worth double-checking what type this object is before you input it to ImpulseDE2.

**Comment by mickmars51** [comment] 2022-06-24 16:22
I am having a similar problem when going through the tutorial using the lsSimulatedData.

**Comment by dswede43** [comment] 2022-07-13 15:30
Yes, I get the exact same error when going through the tutorial.

**Comment by NailouZhang** [comment] 2022-08-29 06:57
This may be caused by the different version of R. impulseDE2 can run well with R 4.0.5, but showing same errors with R version 4.2.1.

**Comment by svigneau** [comment] 2022-09-06 23:10
I had the same problem and proposed a fix [here](https://github.com/YosefLab/ImpulseDE2/pull/34).

**Comment by davidsebfischer** [comment] 2022-09-14 09:27
Merged into master now!

**Closed by davidsebfischer** 2022-09-14 09:27 UTC
